language: python
sudo: false
python:
- '2.7'
- '3.5'
- '3.6'
env:
- DJANGO="Django>=1.11.0,<1.12.0"
- DJANGO="Django>=2.2,<2.3"
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.2,<2.3"
install:
- pip install -q $DJANGO
- pip install flake8
- pip install coveralls
script:
- flake8 contactus
- python runtests.py
- coverage run --source=contactus runtests.py
after_success:
- coveralls
