name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Build with Makefile
        run: make
